---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-audit-service-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-audit
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector: null
          matchLabels:
            role: hocs-casework
