{{- if .Values.dcuCaseView.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hocs-refresh-dcu-cases-view
  labels:
    role: hocs-refresh-dcu-cases-view
spec:
  schedule: {{ .Values.dcuCaseView.refresh }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: hocs-refresh-dcu-cases-view
            role: hocs-refresh-dcu-cases-view
            database: required
        spec:
          containers:
            - name: hocs-refresh-dcu-cases-view
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: quay.io/ukhomeofficedigital/hocs-toolbox:latest
              command: [ "/bin/sh", "-c" ]
              args:
                - psql -tA -c "REFRESH MATERIALIZED VIEW CONCURRENTLY ${DB_SCHEMA_NAME}.dcu_aggregated_cases; SELECT last_refresh FROM ${DB_SCHEMA_NAME}.dcu_aggregated_cases LIMIT 1;"
              env:
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-audit-rds
                      key: host
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-audit-rds
                      key: name
                - name: DB_SCHEMA_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-audit-rds
                      key: schema_name
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-audit-rds
                      key: user_name
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-audit-rds
                      key: password
          restartPolicy: Never
{{- end }}
