---
hocs-generic-service:
  nameOverride: hocs-search-consumer

  selector:
    outbound:
      required: true

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-search
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      springProfiles: 'aws, consumer'
      elasticPrefix: '{{ .Release.Namespace }}-latest'
      searchQueueName: '{{ .Release.Namespace }}-opensearch-sqs'
