---
hocs-generic-service:
  nameOverride: hocs-queue-tool

  selector:
    outbound:
      required: true
    database:
      required: true

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-queue-tool
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=70 -XX:MaxRAMPercentage=70
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      queues: []
