---
hocs-generic-service:
  nameOverride: hocs-queue-tool

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-queue-tool
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      queues: []
