---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-templates-service-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-templates
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-frontend
  egress:
    - ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-docs
        - podSelector:
            matchLabels:
              role: hocs-info-service
