---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-extracts-service-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-extracts
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-info-service
