---
hocs-generic-service:
  nameOverride: hocs-templates

  deployment:
    annotations:
      downscaler/downtime: 'Mon-Sun 00:00-04:50 Europe/London,Mon-Sun 23:05-24:00 Europe/London'

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-templates
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      caseService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      docsService: https://hocs-docs.{{ .Release.Namespace }}.svc.cluster.local
