---
hocs-generic-service:
  nameOverride: hocs-notify

  selector:
    outbound:
      required: true

  networkpolicy:
    enabled: true
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-info-service

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-notify
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sqs'
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
