---
hocs-generic-service:
  nameOverride: hocs-search-multiple
  role: hocs-search

  selector:
    outbound:
      required: true

  networkpolicy:
    enabled: true
    ingress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-casework

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-search
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      springProfiles: 'aws'
      elasticPrefix: ''
      elasticMode: 'MULTIPLE'
      searchQueueName: '{{ .Release.Namespace }}-search-sqs'
