apiVersion: v1
kind: Service
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    service: {{ include "hocs-app.name" . }}
    name: {{ include "hocs-app.name" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    name: {{ include "hocs-app.name" . }}
