apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    version: {{ .Values.version }}
  annotations: {{- toYaml .Values.deployment.annotations | nindent 4 }}
spec:
  {{- if not .Values.autoscale.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ include "hocs-app.name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "hocs-app.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - { { include "hocs-app.name" . } }
                topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ include "hocs-app.name" . }}
          image: '{{ .Values.app.image.repository }}:{{ .Values.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: hocs-queue-config
          resources: {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 2
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 2
          volumeMounts: {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.app.preStop }}
      volumes: {{- toYaml .Values.deployment.volumes | nindent 8 }}
