---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-matchlabel-outbound-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-outbound-proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3129
          protocol: {{ .Values.service.protocol }}
      from:
      - podSelector:
          matchLabels:
            outbound: required
  egress:
    - {}
