---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-outbound-proxy-policy
spec:
  podSelector:
    matchLabels:
      outbound: required
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 3129
          protocol: {{ .Values.service.protocol }}
      to:
        - podSelector:
            matchLabels:
              role: hocs-outbound-proxy
