---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-matchlabel-database-policy
spec:
  podSelector:
    matchLabels:
      database: required
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 5432
          protocol: {{ .Values.service.protocol }}
        - port: 1433
          protocol: {{ .Values.service.protocol }}
      to:
{{- $cidr := splitList "," .Values.rdsCIDR }}
{{- range $cidr }}
        - ipBlock:
            cidr: {{ . | quote }}
{{- end }}
