---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-matchlabel-ingress-policy
spec:
  podSelector:
    matchLabels:
      ingress: required
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
        - namespaceSelector:
            matchLabels:
              name: ingress-internal
