---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-database-policy
spec:
  podSelector:
    matchLabels:
      database: required
  policyTypes:
  - Egress
  egress:
    - ports:
        - port: 5432
          protocol: {{ .Values.service.protocol }}
      to:
        - ipBlock:
            cidr: '{{ .Values.rdsCIDR | quote }}'
