---
hocs-generic-service:
  nameOverride: hocs-case-migrator

  selector:
    outbound:
      required: true
    database:
      required: true

  networkpolicy:
    enabled: true
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-workflow
        - podSelector:
            matchLabels:
              role: hocs-docs

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-case-creator
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      springProfiles: 'sqs, s3, migration'
      caseworkService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local
      workflowService: https://hocs-workflow.{{ .Release.Namespace }}.svc.cluster.local
      docsService: https://hocs-docs.{{ .Release.Namespace }}.svc.cluster.local
      ignoreMessages: 'false'
