---
hocs-generic-service:
  nameOverride: hocs-workflow

  selector:
    outbound:
      required: true
    database:
      required: true

  networkpolicy:
    enabled: true
    ingress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-case-creator
        - podSelector:
            matchLabels:
              role: hocs-case-migrator
        - podSelector:
            matchLabels:
              role: hocs-frontend
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-docs
        - podSelector:
            matchLabels:
              role: hocs-info-service

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-workflow
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sns'
      caseworkService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      docsService: https://hocs-docs.{{ .Release.Namespace }}.svc.cluster.local
      hocsScreensAdditionalFolders: ''
