---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-case-creator-service-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-case-creator
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: {{ .Values.service.protocol }}
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-workflow
