{{- if .Values.jobs.process.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hocs-case-creator-process-messages-job
  labels:
    role: hocs-case-creator-process-messages-job
spec:
  schedule: {{ .Values.jobs.process.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: hocs-case-creator-process-messages-job
            role: hocs-case-creator-process-messages-job
        spec:
          containers:
            - name: hocs-case-creator-process-messages-job
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: quay.io/ukhomeofficedigital/hocs-base-image:latest
              command: [ "/bin/sh", "-c" ]
              args:
                - "curl -vk https://hocs-case-creator.{{ .Release.Namespace }}.svc.cluster.local/process -H \"User-Agent: Process Messages\" -H \"Content-Type: application/json\" -d \"{ \"maxMessages\": $MAX_MESSAGES }\""
              env:
                - name: MAX_MESSAGES
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Namespace }}-case-creator
                      key: max_messages
          restartPolicy: Never
{{- end }}
