---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-case-creator-process-messages-job-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-case-creator-process-messages-job
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-case-creator
