---
hocs-generic-service:
  nameOverride: hocs-casework

  selector:
    outbound:
      required: true
    database:
      required: true

  networkpolicy:
    enabled: true
    ingress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-case-creator
        - podSelector:
            matchLabels:
              role: hocs-case-migrator
        - podSelector:
            matchLabels:
              role: hocs-extracts
        - podSelector:
            matchLabels:
              role: hocs-frontend
        - podSelector:
            matchLabels:
              role: hocs-info-service
        - podSelector:
            matchLabels:
              role: hocs-management-ui
        - podSelector:
            matchLabels:
              role: hocs-templates
        - podSelector:
            matchLabels:
              role: hocs-workflow
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-audit
        - podSelector:
            matchLabels:
              role: hocs-docs
        - podSelector:
            matchLabels:
              role: hocs-info-service
        - podSelector:
            matchLabels:
              role: hocs-search

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-casework
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=70 -XX:MaxRAMPercentage=70
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      springProfiles: 'sqs, sns'
      auditService: https://hocs-audit.{{ .Release.Namespace }}.svc.cluster.local
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      searchService: https://hocs-search.{{ .Release.Namespace }}.svc.cluster.local
      docsService: https://hocs-docs.{{ .Release.Namespace }}.svc.cluster.local
      # The 'real' migration values need to be in a secret
      migrationUserId: cms
      migrationUserName: migration
      migrationGroup: cms
