---
hocs-generic-service:
  nameOverride: hocs-extracts

  selector:
    ingress:
      required: true
    outbound:
      required: true
    database:
      required: true

  networkpolicy:
    enabled: true
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-casework-readonly
        - podSelector:
            matchLabels:
              role: hocs-info-service

  proxy:
    enabled: true
    env:
      - name: HTTP2
        value: 'TRUE'
      - name: PROXY_SERVICE_HOST_1
        value: '127.0.0.1'
      - name: PROXY_SERVICE_PORT_1
        value: '8080'
      - name: PROXY_SERVICE_HOST_2
        value: '127.0.0.1'
      - name: PROXY_SERVICE_PORT_2
        value: '8081'
      - name: LOCATIONS_CSV
        value: '/, /export/'
      - name: NAXSI_USE_DEFAULT_RULES
        value: 'FALSE'
      - name: ENABLE_UUID_PARAM
        value: 'FALSE'
      - name: HTTPS_REDIRECT
        value: 'FALSE'
      - name: SERVER_CERT
        value: /certs/tls.pem
      - name: SERVER_KEY
        value: /certs/tls-key.pem
      - name: ADD_NGINX_HTTP_CFG
        value: >
          client_header_buffer_size 8k;
          fastcgi_buffer_size 128k;
          fastcgi_buffers 16 64k;
          large_client_header_buffers 4 128k;
          proxy_buffer_size 128k;
          proxy_buffers 4 64k;
          proxy_busy_buffers_size 128k;
          proxy_connect_timeout {{ .Values.keycloak.timeout }};
          proxy_read_timeout {{ .Values.keycloak.timeout }};
          proxy_send_timeout {{ .Values.keycloak.timeout }};

  keycloak:
    enabled: true
    args:
      - --config=/etc/secrets/data.yml
      - --discovery-url={{ .Values.keycloak.realm }}
      - --openid-provider-proxy=http://hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local:31290
      - --enable-logging=true
      - --enable-json-logging=true
      - --upstream-url=http://127.0.0.1:{{ include "hocs-app.port" . }}
      - --upstream-response-header-timeout={{ .Values.keycloak.timeout }}s
      - --upstream-expect-continue-timeout={{ .Values.keycloak.timeout }}s
      - --upstream-keepalive-timeout={{ .Values.keycloak.timeout }}s
      - --server-idle-timeout={{ .Values.keycloak.timeout }}s # default 120s
      - --server-read-timeout={{ .Values.keycloak.timeout }}s
      - --server-write-timeout={{ .Values.keycloak.timeout }}s
      - --resources=uri=/export/MIN*|roles=DCU_EXPORT_USER
      - --resources=uri=/export/TRO*|roles=DCU_EXPORT_USER
      - --resources=uri=/export/DTEN*|roles=DCU_EXPORT_USER
      - --resources=uri=/export/WCS*|roles=WCS_EXPORT_USER
      - --resources=uri=/export/MPAM*|roles=MPAM_EXPORT_USER
      - --resources=uri=/export/MTS*|roles=MPAM_EXPORT_USER
      - --resources=uri=/export/COMP*|roles=COMP_EXPORT_USER
      - --resources=uri=/export/FOI*|roles=FOI_EXPORT_USER
      - --resources=uri=/export/TO*|roles=TO_EXPORT_USER
      - --resources=uri=/export/BF*|roles=BF_EXPORT_USER
      - --resources=uri=/export/IEDET*|roles=IEDET_EXPORT_USER
      - --resources=uri=/export/POGR*|roles=POGR_EXPORT_USER
      - --resources=uri=/export/somu/FOI*|roles=FOI_EXPORT_USER
      - --resources=uri=/export/somu/MPAM*|roles=MPAM_EXPORT_USER
      - --resources=uri=/export/somu/COMP*|roles=COMP_EXPORT_USER
      - --resources=uri=/export/somu/TO*|roles=TO_EXPORT_USER
      - --resources=uri=/export/somu/BF*|roles=BF_EXPORT_USER
      - --resources=uri=/export/somu/POGR*|roles=POGR_EXPORT_USER
      - --resources=uri=/export/topics*|roles=DCU_EXPORT_USER,FOI_EXPORT_USER|require-any-role=true
      - --resources=uri=/export/teams*|roles=DCU_EXPORT_USER,WCS_EXPORT_USER,MPAM_EXPORT_USER,COMP_EXPORT_USER,FOI_EXPORT_USER,IEDET_EXPORT_USER,BF_EXPORT_USER,POGR_EXPORT_USER|require-any-role=true
      - --resources=uri=/export/users*|roles=DCU_EXPORT_USER,WCS_EXPORT_USER,MPAM_EXPORT_USER,COMP_EXPORT_USER,FOI_EXPORT_USER,IEDET_EXPORT_USER,BF_EXPORT_USER,POGR_EXPORT_USER|require-any-role=true
      - --resources=uri=/export/custom/*/refresh|methods=POST|white-listed=true
      - --secure-cookie=true
      - --http-only-cookie=true
      - --enable-default-deny=true
      - --enable-refresh-tokens=true
      - --encryption-key=$(ENCRYPTION_KEY)
      - --no-redirects=false
      - --enable-logout-redirect=true
      - --listen=127.0.0.1:{{ .Values.keycloak.targetPort }}
      - --revocation-url={{ .Values.keycloak.realm }}/protocol/openid-connect/logout
    timeout: 300

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-audit
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ include "cs-namespace" . }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.svc.cluster.local
      springProfiles: 'extracts'
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      caseworkService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local

dcuCaseView:
  enabled: false
