---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-docs-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-docs
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: hocs-frontend
        - podSelector:
            matchLabels:
              role: hocs-backend
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: virus-scan
    - to:
        - podSelector:
            matchLabels:
              role: hocs-docs-converter
