---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-extracts-policy
spec:
  podSelector:
    matchLabels:
      name: hocs-extracts
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
