---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-frontend-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-frontend-policy-internal
spec:
  podSelector:
    matchLabels:
      role: hocs-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
