---
nameOverride: hocs-toolbox

selector:
  ingress:
    required: false
  outbound:
    required: true
  database:
    required: true

deployment:
  selectorRole: hocs-backend
  replicas: 1
  securityContext:
    runAsNonRoot: true
    capabilities:
      drop:
        - SETUID
        - SETGID

app:
  image:
    repository: quay.io/ukhomeofficedigital/hocs-toolbox
  env:
    databases:
      - 'audit'
      - 'info'
      - 'docs'
      - 'workflow'
      - 'casework'
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
