---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-opensearch-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-search
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-casework
