---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-docs-service-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-docs
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-frontend
        - podSelector:
            matchLabels:
              role: hocs-info-service
        - podSelector:
            matchLabels:
              role: hocs-management-ui
        - podSelector:
            matchLabels:
              role: hocs-templates
        - podSelector:
            matchLabels:
              role: hocs-workflow
  egress:
    - ports:
        - port: 10443
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              name: virus-scan
        - namespaceSelector:
            matchLabels:
              name: hocs-converter
