apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    version: {{ .Values.version }}
  annotations: {{- toYaml .Values.deployment.annotations | nindent 4 }}
spec:
  {{- if not .Values.autoscale.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ include "hocs-app.name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "hocs-app.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - {{ include "hocs-app.name" . }}
                topologyKey: kubernetes.io/hostname
      initContainers:
        {{- if .Values.truststore.enabled }}
        - name: truststore
          image: '{{ .Values.truststore.image.repository }}:{{ .Values.truststore.image.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          args: {{- tpl (toYaml .Values.truststore.args) . | nindent 12 }}
          volumeMounts: {{- toYaml .Values.truststore.volumeMounts | nindent 12 }}
          resources: {{- toYaml .Values.truststore.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.data.enabled }}
        - name: hocs-info-service-data-migration
          image: '{{ .Values.data.image.repository }}{{ .Values.data.image.name }}:{{ .Values.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env:
            {{- include "hocs-info-service-data.envs" . | nindent 12 }}
          resources: {{- toYaml .Values.data.resources | nindent 12 }}
        {{- end }}
      containers:
        - name: {{ include "hocs-app.name" . }}
          image: '{{ .Values.app.image.repository }}:{{ .Values.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: hocs-queue-config
          env:
            {{- include (printf "%s.%s" .Values.nameOverride "envs") . | nindent 12 }}
          resources: {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ include "hocs-app.port" . }}
          startupProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.liveness }}
              port: http
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.liveness }}
              port: http
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.readiness }}
              port: http
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: 2
          volumeMounts: {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.app.preStop }}
      volumes: {{- toYaml .Values.deployment.volumes | nindent 8 }}
