{{- if .Values.members.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hocs-refresh-members-job
spec:
  schedule: {{ .Values.members.refresh }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: hocs-refresh-members-job
            role: hocs-backend
        spec:
          containers:
            - name: hocs-refresh-members-job
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: quay.io/ukhomeofficedigital/hocs-base-image:latest
              env:
                - name: HOCS_BASICAUTH
                  valueFrom:
                    secretKeyRef:
                      name: ui-casework-creds
                      key: plaintext
              command: [ "/bin/sh", "-c" ]
              args:
                - "curl -vk -X POST -u ${HOCS_BASICAUTH} -H 'User-Agent: Refresh Members' https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local/admin/member/refresh"
          restartPolicy: Never
{{- end }}
