---
hocs-generic-service:
  nameOverride: hocs-search-multiple-consumer

  selector:
    outbound:
      required: true

  service:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-search
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'aws, consumer'
      elasticPrefix: ''
      elasticMode: 'MULTIPLE'
      searchQueueName: '{{ .Release.Namespace }}-search-sqs'
