---
hocs-generic-service:
  nameOverride: hocs-audit

  selector:
    outbound:
      required: true
    database:
      required: true

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-audit
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=65
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sqs, consumer'

dcuCaseView:
  enabled: false
  refresh: '30 5 * * *'
