---
hocs-generic-service:
  nameOverride: hocs-docs-converter

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-docs-converter
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=50
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
