---
hocs-generic-service:
  nameOverride: hocs-docs-converter

  networkpolicy:
    enabled: true
    ingress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-docs-converter
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=50
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
