{{- if .Values.autoscale.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ include "hocs-app.name" . }}
  name: {{ include "hocs-app.name" . }}
spec:
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hocs-app.name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscale.targetCpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscale.targetMemory }}
{{- end }}
