apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    version: {{ .Values.version }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
spec:
  {{- if not .Values.autoscale.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ include "hocs-app.name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "hocs-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.truststore.enabled }}
        - name: truststore
          image: '{{ .Values.truststore.image.repository }}:{{ .Values.truststore.image.version }}'
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          args:
            {{ include "truststore.envs" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.truststore.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.truststore.resources | nindent 12 }}
        {{- end }}
      containers:
        {{- if .Values.proxy.enabled }}
        - name: proxy
          image: '{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.version }}'
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env:
            {{ include "proxy.envs" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.proxy.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.keycloak.enabled }}
        - name: keycloak
          image: '{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.version }}'
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env:
            {{ include "keycloak.envs" . | nindent 12 }}
          args:
            - --no-redirects=false
            - --enable-logout-redirect=true
            - --listen=127.0.0.1:{{ .Values.keycloak.targetPort }}
            - --revocation-url={{ .Values.keycloak.realm }}/protocol/openid-connect/logout
            {{ include "keycloak.args" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.keycloak.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.keycloak.targetPort }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.keycloakApi.enabled }}
        - name: keycloak-proxy-api
          image: '{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.version }}'
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env:
            {{ include "keycloak.envs" . | nindent 12 }}
          args:
            - --no-redirects=true
            - --listen=127.0.0.1:{{ .Values.keycloakApi.targetPort }}
            {{ include "keycloak.args" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.keycloak.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.keycloakApi.targetPort }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
        {{- end }}
        - name: {{ include "hocs-app.name" . }}
          image: '{{ .Values.app.image.repository }}:{{ .Values.version }}'
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: hocs-queue-config
          env:
            {{ include "deployment.envs" . | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ include "hocs-app.port" . }}
          {{ include "healthcheck.envs" . | nindent 10 }}
          volumeMounts:
            {{- toYaml .Values.app.volumeMounts | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.app.preStop }}
      volumes:
        {{- toYaml .Values.deployment.volumes | nindent 8 }}
