apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    version: {{ .Values.version }}
  annotations: {{- toYaml .Values.deployment.annotations | nindent 4 }}
spec:
  {{- if not .Values.autoscale.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ include "hocs-app.name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "hocs-app.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - {{ include "hocs-app.name" . }}
                topologyKey: kubernetes.io/hostname
      initContainers:
        {{- if .Values.truststore.enabled }}
        - name: truststore
          image: '{{ .Values.truststore.image.repository }}:{{ .Values.truststore.image.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          args: {{- tpl (toYaml .Values.truststore.args) . | nindent 12 }}
          volumeMounts: {{- toYaml .Values.truststore.volumeMounts | nindent 12 }}
          resources: {{- toYaml .Values.truststore.resources | nindent 12 }}
        {{- end }}
      containers:
        {{- if .Values.proxy.enabled }}
        - name: proxy
          image: '{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env: {{- tpl (toYaml .Values.proxy.env) . | nindent 12 }}
          volumeMounts: {{- toYaml .Values.proxy.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
          resources: {{- toYaml .Values.proxy.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.keycloak.enabled }}
        - name: keycloak
          image: '{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env: {{- tpl (toYaml .Values.keycloak.env) . | nindent 12 }}
          args: {{- tpl (toYaml .Values.keycloak.args) . | nindent 12 }}
          {{- if not .Values.ingress.internal.enabled }}
            - --redirection-url=https://{{ .Values.keycloak.domain }}
            - --cookie-domain=https://{{ .Values.keycloak.domain }}
          {{- end }}
          volumeMounts: {{- toYaml .Values.keycloak.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.keycloak.targetPort }}
          resources: {{- toYaml .Values.keycloak.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.keycloakApi.enabled }}
        - name: keycloak-proxy-api
          image: '{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          env: {{- tpl (toYaml .Values.keycloak.env) . | nindent 12 }}
          args: {{- tpl (toYaml .Values.keycloakApi.args) . | nindent 12 }}
          {{- if not .Values.ingress.internal.enabled }}
            - --redirection-url=https://{{ .Values.keycloak.domain }}
            - --cookie-domain=https://{{ .Values.keycloak.domain }}
          {{- end }}
          volumeMounts: {{- toYaml .Values.keycloak.volumeMounts | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.keycloakApi.targetPort }}
          resources: {{- toYaml .Values.keycloak.resources | nindent 12 }}
        {{- end }}
        - name: {{ include "hocs-app.name" . }}
          image: '{{ .Values.app.image.repository }}:{{ .Values.version }}'
          securityContext: {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          envFrom: {{- toYaml .Values.deployment.envFrom | nindent 12 }}
          env:
            {{- include (printf "%s.%s" (include "hocs-deploymentEnvs.name" .) "envs") . | nindent 12 }}
          resources: {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ include "hocs-app.port" . }}
          startupProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.liveness }}
              port: {{ .Values.service.portName }}
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: {{ .Values.app.healthcheck.startup.initialDelay }}
            periodSeconds: {{ .Values.app.healthcheck.startup.period }}
            failureThreshold: {{ .Values.app.healthcheck.startup.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.liveness }}
              port: {{ .Values.service.portName }}
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: {{ .Values.app.healthcheck.liveness.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.readiness }}
              port: {{ .Values.service.portName }}
              scheme: {{ include "hocs-app.healthcheck.scheme" . }}
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: {{ .Values.app.healthcheck.readiness.period }}
          volumeMounts: {{- tpl toYaml .Values.app.volumeMounts | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.app.preStop }}
      volumes: {{- toYaml .Values.deployment.volumes | nindent 8 }}
        {{- if .Values.keycloak.enabled }}
        - name: {{ .Values.keycloak.secretName }}
          secret:
            secretName: {{ .Values.keycloak.secretName }}
        {{- end }}
