{{- if .Values.ingress.external.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    app: {{ include "hocs-app.name" . }}
    cert-manager.io/solver: http01
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    kubernetes.io/ingress.class: nginx-external
    ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.external.allowedIps }}
spec:
  tls:
  - hosts:
      - {{ include "hocs-app.external.domainName" . }}
    secretName: {{ include "hocs-app.name" . }}-external-tls-cert
  rules:
  - host: {{ include "hocs-app.external.domainName" . }}
    http:
      paths:
        {{- toYaml .Values.ingress.paths | nindent 8 }}
{{- end }}
