{{- if .Values.ingress.internal.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hocs-app.name" . }}-internal
  labels:
    app: {{ include "hocs-app.name" . }}
    cert-manager.io/solver: route53
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    kubernetes.io/ingress.class: nginx-internal
spec:
  tls:
  - hosts:
      - {{ include "hocs-app.internal.domainName" . }}
    secretName: {{ include "hocs-app.name" . }}-internal-tls-cert
  rules:
  - host: {{ include "hocs-app.internal.domainName" . }}
    http:
      paths:
        {{- toYaml .Values.ingress.paths | nindent 8 }}
{{- end }}
