{{- if .Values.ingress.internal.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    kubernetes.io/ingress.class: nginx-internal
  labels:
    cert-manager.io/solver: route53 # internal ingresses can't use http01 as Let's Encrypt can't see it
  name: {{ include "hocs-app.name" . }}-internal
spec:
  rules:
  - host: {{ include "hocs-app.internal.domainName" . }}
    http:
      paths:
        {{- toYaml .Values.ingress.paths | nindent 8 }}
  tls:
  - hosts:
    - {{ include "hocs-app.internal.domainName" . }}
    secretName: hocs-frontend-internal-tls-cert
{{- end }}
