{{- if .Values.networkpolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hocs-app.name" . }}-service-policy
spec:
  podSelector:
    matchLabels:
      role: {{ include "hocs-app.name" . }}
  policyTypes:
    {{- if .Values.networkpolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkpolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkpolicy.ingress.enabled }}
  ingress:
    - ports:
        {{- toYaml .Values.networkpolicy.ingress.ports | nindent 8 }}
      from:
        {{- toYaml .Values.networkpolicy.ingress.from | nindent 8 }}
  {{- end }}
  {{- if .Values.networkpolicy.egress.enabled }}
  egress:
    - ports:
        {{- toYaml .Values.networkpolicy.egress.ports | nindent 8 }}
      to:
        {{- toYaml .Values.networkpolicy.egress.to | nindent 8 }}
  {{- end }}
{{- end }}
