{{- if .Values.networkpolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hocs-app.name" . }}-service-policy
spec:
  podSelector:
    matchLabels:
      role: {{ include "hocs-app.name" . }}
  policyTypes:
    {{- if .Values.networkpolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkpolicy.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        {{- toYaml .Values.networkpolicy.ports | nindent 8 }}
      {{- if .Values.networkpolicy.ingress }}
      from:
        {{- toYaml .Values.networkpolicy.from | nindent 8 }}
      {{- end }}
      {{- if .Values.networkpolicy.egress }}
      to:
        {{- toYaml .Values.networkpolicy.to | nindent 8 }}
      {{- end }}
{{- end }}
