{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    name: {{ include "hocs-app.name" . }}
spec:
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    name: {{ include "hocs-app.name" . }}
{{- end }}
