name: 'Release Charts'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/helm-release-chart.yml@v1
    secrets: inherit
