name: 'Release Charts'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/helm-release-chart.yml@v2
    secrets: inherit
