---
hocs-generic-service:
  nameOverride: hocs-case-creator

  selector:
    outbound:
      required: true
    database:
      required: true

  networkpolicy:
    enabled: true
    ingress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              role: hocs-case-creator-process-messages-job
    egress:
      enabled: true
      ports:
        - port: 10443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              role: hocs-casework
        - podSelector:
            matchLabels:
              role: hocs-workflow
  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-case-creator
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65
        -Dcom.sun.management.jmxremote
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sqs, s3, ukvi'
      caseworkService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local
      workflowService: https://hocs-workflow.{{ .Release.Namespace }}.svc.cluster.local
      ignoreMessages: 'false'

jobs:
  process:
    enabled: false
    schedule: '0 8-18 * * 1-5'
